import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:provider/provider.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:http/http.dart' as http;

// ── Generated by `flutterfire configure` — run that command once first ────────
// import 'firebase_options.dart';
// ─────────────────────────────────────────────────────────────────────────────

import 'core/app_config.dart';
import 'app.dart';
import 'providers/auth_provider.dart' as core;
import 'providers/diagnosis_history_provider.dart';
import 'providers/journal_provider.dart';
import 'providers/user_stats_provider.dart';
import 'providers/theme_provider.dart';
import 'services/revenue_cat_service.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ── Step 1: Firebase ───────────────────────────────────────────────────────
  // After running `flutterfire configure`, replace the line below with:
  // await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  await Firebase.initializeApp();

  // ── Step 2: RevenueCat ─────────────────────────────────────────────────────
  await RevenueCatService.initialize();

  // ── Step 3: System UI ──────────────────────────────────────────────────────
  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      statusBarColor:           Colors.transparent,
      statusBarIconBrightness:  Brightness.light,
    ),
  );

  // ── Silently warm up the backend on Render (prevents cold-start delay) ─────
  try {
    http
        .get(Uri.parse('${AppConfig.baseUrl}/health'))
        .timeout(const Duration(seconds: 5));
  } catch (_) {}

  final prefs          = await SharedPreferences.getInstance();
  final onboardingDone = prefs.getBool('onboarding_done') ?? false;

  final diagnosisProvider = DiagnosisHistoryProvider();
  final journalProvider   = JournalProvider();
  final statsProvider     = UserStatsProvider();
  final themeProvider     = ThemeProvider();

  await journalProvider.load();
  await statsProvider.load();

  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => core.AuthProvider()),
        ChangeNotifierProvider.value(value: diagnosisProvider),
        ChangeNotifierProvider.value(value: journalProvider),
        ChangeNotifierProvider.value(value: statsProvider),
        ChangeNotifierProvider.value(value: themeProvider),
      ],
      child: CoreApp(showOnboarding: !onboardingDone),
    ),
  );
}
